# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddwww < Formula
  desc "development static web server"
  homepage "https://github.com/denisdefreyne/ddwww"
  version "0.1.1"
  license "Hippocratic License 3.0"

  depends_on "shadowenv"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/denisdefreyne/ddwww/releases/download/v0.1.1/ddwww_Darwin_x86_64.tar.gz"
    sha256 "923e0fca5ff1f1cee0ad3b019498a6d818d1cd7d21731234728819c036014392"

    def install
      bin.install "ddwww"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/denisdefreyne/ddwww/releases/download/v0.1.1/ddwww_Darwin_arm64.tar.gz"
    sha256 "4935e11e1b3bd92d55ed345ef1dfa28d5bd9e740ff755df1fde86c12f798247e"

    def install
      bin.install "ddwww"
    end
  end

  test do
    system "#{bin}/task", "--help"
  end
end
